### ISSUE TITLE
A-RT.70.99.99 / Linea di montaggio Platypus

### ISSUE THREAD

**Issue by polaeros** [Diamond-SA/Meccanica#18]
Richiedente: R.Ferrari (int. 460)

- [x] Disegnare attrezzatura per inserimento chiodini
- [x] Ripristinare attrezzatura per inserimento chiodini
- [x] Disegnare attrezzature
- [x] Realizzare attrezzature

**Comment by polaeros** [comment]
19.08.2022
Attrezzatura in TR per modifica

**Comment by Etica27** [comment]
I disegni per la fabbricazione dei pezzi sono stati consegnati al richiedente e un primo esemplare è stato assemblato.
