### ISSUE TITLE
A-RT.70.99.99 / Postazione di pulizia e smussatura ceramica

### ISSUE THREAD

**Issue by polaeros** [Diamond-SA/Meccanica#26]
Richiedente: G.Papale (int. 403)

- [x] Progettazione postazione di pulizia pezzi in ceramica
- [x] Presentare apparecchiatura a T/P/QA
- [x] Studio di fattibilità per eventuali nuove richieste
- [x] Realizzazione macchina

**Comment by bricalli-m** [comment]
Dopo riunione del 24.08.22 si è deciso di proseguire con la postazione autocostruita, ottimizzandola ed integrandola al meglio nel reparto. 

[G095_Verbale_riunione_24.08.22.docx](https://github.com/Diamond-SA/TC/files/9422014/G095_Verbale_riunione_24.08.22.docx)

- [x] Analisi del processo di lavoro (minimizzare e rendere fluido il lavoro dell'operatore)
- [x] Analisi degli spazi (posizione nel reparto, dimensioni della postazione)
- [x] Analisi ergonomica (altezza, visibilità, macchina regolabile) *vedere anche norme SUVA
- [x] Ricerca soluzioni
- [x] Ottimizzazione macchina 3D (applicare le modifiche al modello)

**Comment by bricalli-m** [comment]
Di seguito il verbale della riunione:

[G095_Verbale_riunione_14.09.2022.docx](https://github.com/Diamond-SA/TC/files/9566721/G095_Verbale_riunione_14.09.2022.docx)

Riassunto verbale:
-	Realizzare 2 esemplari di macchina oppure ottimizzarla per l’utilizzo sincrono
-	Prevedere l’acquisto di un’aspirapolvere hobbistica per adibirla alla macchina
-	Semplificare l’attacco dell’aspirazione se vi è un'aspirapolvere adibita 
-	Ampliare il diametro massimo temperabile dalla smussatrice (>10mm)
-	Semplificare e ottimizzare la forma delle lame del temperino (temprare)

**Comment by bricalli-m** [comment]
Prossimi passi:
- [x] Accettazione Budget
- [x] Ordinare materiale
- [x] Realizzazione schema pneumatico
- [x] Realizzazione schema elettrico
- [x] Fabbricazione componenti
- [x] Montaggio e cablaggio
- [x] Messa in servizio
